spring:
  datasource:
    username: project_tracker
    password: project_tracker
    url: jdbc:mysql://localhost:3306/project_tracker
  
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
    
  sql:
    init:
      mode: always
      
logging:
  level:
    root: info
    project_tracker: debug  